swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions/{accountNumber}:
    get:
      tags:
        - Transaction Module
      summary: Get Transactions
      description: Retrieve all transactions for the specified account for the current month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountNumber
          description: Account number for which transactions are requested
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
          examples:
            application/json:
              transactions:
                - id: "1"
                  date: "2024-01-01T09:15:00.123Z"
                  description: "Transaction description"
                  amount: 100.50
                  balance: 1500.20
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions/{accountNumber}/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Get Transaction Details
      description: Retrieve details of a specific transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountNumber
          description: Account number for which transaction details are requested
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the specific transaction to be requested
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
          examples:
            application/json:
              id: "1"
              date: "2024-01-01T09:15:00.123Z"
              description: "Transaction description"
              amount: 100.50
              balance: 1500.20
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transaction Module
      summary: Update Transaction
      description: Update category and note fields of a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountNumber
          description: Account number for which transaction details are requested
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the specific transaction to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
          examples:
            application/json:
              status: 200
              message: "Transaction updated successfully"
              body:
                id: "1"
                date: "2024-01-01T09:15:00.123Z"
                description: "Updated transaction description"
                amount: 100.50
                balance: 1500.20
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsResponse:
    type: object
    properties:
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date-time
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
  TransactionDetailsResponse:
    $ref: '#/definitions/Transaction'
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
      note:
        type: string
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
            format: date-time
          description:
            type: string
          amount:
            type: number
          balance:
            type: number
